version: 2.1

jobs:
  job-1:
    executor: my-ubuntu-exec
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
  job-2:
    executor: my-ubuntu-exec
    steps:
      - checkout
      - run: npm ci
      - run: npm run cy:run

workflows:
  version: 2
  test:
    jobs:
      - job-1
      - job-2:
          requires:
            - job-1