version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  test:
  jobs:
    job-1:
      docker:
        - image: ubuntu:latest
      steps:
        - checkout
        - run: apt-get update
        - run: apt-get install -y npm
        - run: npm init
        - run: npm install
        - run: npm run build
        - run: npm ci
        - run: npm run lint