version: 2.1

jobs:
  verification:
    docker:
      - image: cypress/base
    steps:
      - checkout
      - run: npm install
      - run:
          name: verification lint
          command: npm run lint
  test:
    docker:
      - image: cypress/base
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Cypress tests
          command: npx cypress run
      - run:
          name: Concatenate JSON reports
          command: |
            npm install -g mochawesome-merge
            mochawesome-merge path/to/json/*.json > merged-report.json

      # Génération du rapport HTML
      - run:
          name: Generate HTML report
          command: |
            npm install -g mochawesome-report-generator
            marge merged-report.json 
 
  # Configuration des artifacts
  artifacts:
    # Définition des fichiers à archiver
    paths:
      - merged-report.json
      - mochawesome.html
workflows:
  verification_test:
    jobs:
      - verification
      - test:
          requires:
            - verification
      - artifacts:
          requires:
            - test