version: 2.1
jobs:
  verification:
    docker:
      - image: cypress/base
    steps:
      - checkout
      - run: npm install
      - run:
          name: verification lint
          command: npm run lint
  test:
    docker:
      - image: cypress/base
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Cypress tests
          command: npx cypress run
workflows:
  verification_test:
    verification:
      jobs:
      - verification:
      - test:
          requires:
            - verification: