version: 2.1

jobs:
  verification:
    executor: my-ubuntu-exec
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
  test:
    executor: my-ubuntu-exec
    steps:
      - checkout
      - run: npm ci
      - run: npm run cy:run

workflows:
  my_workflow:
    jobs:
      - verification
      - cypress-test:
          requires:
            - verification