version: 2.1


jobs:
  job-1:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y npm
      - run: npm init
      - run: npm install
      - run: npm run build
      - run: npm ci
      - run: npm run lint
  job-2:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: npm ci
      - run: npm run cy:run

workflows:
  version: 2
  test:
    jobs:
      - job-1
      - job-2:
          requires:
            - job-1