version: 2.1

jobs:
  verification:
    docker:
      - image: cypress/base
    steps:
      - checkout
      - run: npm install
      - run:
          name: verification lint
          command: npm run lint
  test:
    docker:
      - image: cypress/base
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Cypress tests
          command: npx cypress run
  post-steps:
    docker:
      - image: cypress/base
    steps:
      - checkout
      - run: npm install
      - run:
          name: Create merged-report Directory
          command: mkdir cypress/merged-report/
      - run:
          name: Merge mochawesome jsons in one file
          when: always
          command: npx mochawesome-merge --reportDir cypress/results > cypress/merged-report/merged-report.json
      - run:
          name: Generate mochawesome html report
          when: always
          command: npx marge cypress/merged-report/merged-report.json -o cypress/mochawesome-html-report
      - store_artifacts:
          name: Uploading mochawesome-merged-report.json
          path: cypress/merged-report
      - store_artifacts:
          name: Uploading mochawesome-html-report
          path: cypress/mochawesome-html-report
workflows:
  verification_test:
    jobs:
      - verification
      - test:
          requires:
            - verification
      - post-steps:
          requires:
            - test
          if: always()